### PR TITLE
My simple portfolio 1

### PR DESCRIPTION
**Pull request by monicah79**
- Added images.
- Added linters.
- Created index.html.
- Create css file.
- Followed Figma design.

### CODE REVIEW

**Review by OyePriscilla — CHANGES_REQUESTED** [review]
## Hi @monicah79  😄,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has all other files content in a submodule. Due to this reason, I cannot access the good work you've done so far! Kindly put all your files in the root folder not .github folder. You can check your commit history; commit other files to the branch as you've rightly done for style.css. 😄 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by monicah79** [comment]
hehehehe i dont get it,,,,if you dont mind just let me know what to do

**Comment by OyePriscilla** [comment]
Kindly check your commit history on this branch [my-simple-portfolio-1](https://github.com/monicah79/my-personal-portfolio/tree/my-simple-portfolio-1) and commit other files to github the way you commit style.css; other files were added to .github folder. 
ddd

**Comment by monicah79** [comment]
Got it, thanks! so how do i undo it

**Pull request closed without merging**
