### PR TITLE
form validation

### PR DESCRIPTION
**Pull request by monicah79**
- Created form validation
- Followed figma design
- Added js  file

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @monicah79, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Ouch-gifs-38715704-365-199


You have submitted a project that's not having the proper linters setup. Kindly note that the [linters setup for HTML, CSS and Javascript](https://github.com/microverseinc/linters-config/blob/master/html-css-js) is the proper setup to be used now that the project involves JavaScript.

Also, this is a pair programming project, however, only one member of the team has a commit. Every team member is required to be part of the project which will be evidenced by their commits.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by emmiiorji** [comment]
Hi @monicah79

For the linters, because JavaScript is now involved, you need to use the right linters in order to check your scripts. Kindly follow the link and update the necessary files while creating the ones that were not existing before and then run the given commands.

**Comment by monicah79** [comment]
Thank you for the clarification.

**Comment by monicah79** [comment]
bt i have them

**Comment by emmiiorji** [comment]
Compare the file content, they're not exactly the same.. For example: here's your [linters.yml](https://github.com/monicah79/my-personal-portfolio/blob/form-validation/.github/workflows/linters.yml) and here's the [correct linters.yml](https://github.com/microverseinc/linters-config/blob/master/html-css-js/.github/workflows/linters.yml) for project including JavaScript

**Comment by monicah79** [comment]
Got it, thanks!

**Review by franclobo — APPROVED** [review]
Hi @monicah79, 

# STATUS: APPROVED 😃 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional READme file ✔️ 
- The contact form works as expected 💯 

## Optional suggestions

- [ ] **[OPTIONAL]** Kindly correct the contrast of the text in the text box for a better user interface, when I wrote the message I couldn't see the text. 👇🏽 

image

- [ ] **[OPTIONAL]** ⚠️ Kindly review the announcements in the Slack channel they informed us about a change in the [README template](https://github.com/microverseinc/readme-template) **IT IS GOING TO BE MANDATORY NEXT WEEK** ⚠️

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
